backend:
  name: github
  repo: clovyclov/dumpsters911
  branch: main

media_folder: "public/assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Dumpsters 911 Team" }
      - { label: "Hero Image", name: "heroImage", widget: "image" }
      - { label: "Category", name: "category", widget: "select", options: ["Home Improvement", "Commercial Waste", "Landscaping", "Dumpster Sizing", "Metro Detroit News"] }
      - { label: "Post Excerpt", name: "excerpt", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
